### ISSUE TITLE
eclcc auto selection picked sub optimal compiler.

### ISSUE THREAD

**Issue by iMikePayne** [hpcc-systems/vscode-ecl#100]
Error free code failing after being submitted. Open same file in ECL IDE and submits/completes just fine. 0.0.28

**Comment by iMikePayne** [comment]
Error in ECL watch is "Object '**myfolder**' does not have a member named '**myfile**'"

The file within the folder exists. Runs fine using ECL IDE.

Also gives a path with an extra period and slash. Don't know if that has anything to do with it.

C:\Users\iMikePayne\Docs\WorkingDir\**.\**MyFolder\MySubFolder\Base.ecl

**Comment by GordonSmith** [comment]
This sounds like your setting the root folder at the wrong level in vscode?

If your structure is:
```
git/
    MyModA
    MyModB
```

You should not set "git" as the base folder.

You should create a new "workspace" and add both ModA and ModB as root folders.

(You can do this by opening "MyModA" as a root folder and then dragging "MyModB" into the tree)

**Comment by iMikePayne** [comment]
Workspace setup isn't the issue. I've had this setup for over 6 months now. This only happens with certain files. Other files at the same depth referencing same imports work fine. Just started recently.

**Comment by GordonSmith** [comment]
VSCode was picking the wrong compiler (Updating title to reflect same).
