### ISSUE TITLE
Launch is failing with valid user id and password

### ISSUE THREAD

**Issue by gmarcan** [hpcc-systems/vscode-ecl#112]
Since 0.030 (or within couple of days), whenever I open the IDE I am able, within a minute or less submit a workunit. It is able to read the launch setting correctly and submit the wuid. However, after that, VS code starts asking for user id and password repeatedly and then fails to launch with a popup message: "Invalid user ID / password" (regardless if valid user id and password is provided).

Please let me know if you need more information on my setup.

**Comment by GordonSmith** [comment]
This is with an ID + PW set in your launch file?

**Comment by GordonSmith** [comment]
Also can you doublecheck that you don't have two launch configurations with the same name?

**Comment by gmarcan** [comment]
I will check regarding multiples (although I don't think so). It fails whether I specify user ID and passwod within the launch configuration, or if I use a configured parameter from the workspace settings. Also, I am able to launch multiple wuids until it reaches the point where it starts asking for the credentials.

**Comment by GordonSmith** [comment]
Should be resolved with:  https://github.com/hpcc-systems/vscode-ecl/pull/114

**Comment by gmarcan** [comment]
Confirmed. Version 0.0.35 is no longer prompting for user id and password if one is provided in the launch settings file. However, if the password or user id (or both) are left blank ( "" ) - the prompt does not seem to process valid credentials correctly on-the-fly. Not sure if this is a priority though. **Regardless, thank you for fixing the original issue.**
