### ISSUE TITLE
Self signed certificates not allowed

### ISSUE THREAD

**Issue by arcadigonzalez-work** [hpcc-systems/vscode-ecl#116]
When targeting our dev cluster (it uses a self signed certificate) I'm getting the following error:
`Launch failed - Error: 0:  request to https://domain.com:18010/WsSMC/Activity.json failed, reason: self signed certificate
`
Running 0.0.35 on windows, with `"rejectUnauthorized": false`

The connection works when using ECL IDE

**Comment by GordonSmith** [comment]
It would be better if you added that specific certificate to your local trusted store?
