### ISSUE TITLE
VS-Code cannot connect to a server using userNameOnly authentication

### ISSUE THREAD

**Issue by JamesDeFabia** [hpcc-systems/vscode-ecl#124]
If you submit a job to a system where ESP is set to use userNameOnly as its authentication method, then VS-Code prompts for username AND password. If you provide a username and hit enter for a blank password, it responds with an Invalid credential error.
@kunalaswani

**Comment by GordonSmith** [comment]
@JamesDeFabia Can you point me to where I can set that in configmgr?

**Comment by JamesDeFabia** [comment]
In the ESP component, the Authentication Tab, there is a droplist for Method. select userNameOnly

**Comment by GordonSmith** [comment]
Can you confirm this is resolved with the latest release?

**Comment by GordonSmith** [comment]
Resolved with:  https://github.com/hpcc-systems/vscode-ecl/pull/125
