### ISSUE TITLE
Auto-complete for modules doesn't pick up names prefixed with '_'

### ISSUE THREAD

**Issue by dcamper** [hpcc-systems/vscode-ecl#144]
Example line of code:

publicRecordsData := DataDetectors.DataSource._Files.PublicRecordsHeader.FILE;

When typing this, auto-complete fails to show the _Files module or another eligible module named '_Base'.  After '_Files.' is entered, however, auto-complete starts working agin.

**Comment by GordonSmith** [comment]
I am unable to reproduce:
![image](https://user-images.githubusercontent.com/966863/73117352-567f6a80-3f3c-11ea-8ce2-d45ebed3383e.png)

Maybe its specfic to libs / bundles?

**Comment by dcamper** [comment]
I am unable to reproduce as well.  This issue was opened very long ago and many things have changed, so I am not surprised.  Closing for now; will reopen if the issue pops up again.
