### ISSUE TITLE
F12 to follow definition stopped working with latest update. 1.1.4

### ISSUE THREAD

**Issue by wgehalo** [hpcc-systems/vscode-ecl#148]
Whether fully qualified or using $. notation, the f12 key reports "no definition found" since I updated the extension to 1.1.4 today.

**Comment by wgehalo** [comment]
`Name: ECL Language
Id: hpcc-systems.ecl
Description: ECL (Enterprise Control Language) support for Visual Studio Code
Version: 1.1.4
Publisher: HPCC Systems
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=hpcc-systems.ecl

**Comment by GordonSmith** [comment]
Dup of #149
