### ISSUE TITLE
F12 Feature Not working

### ISSUE THREAD

**Issue by kattasravankumar** [hpcc-systems/vscode-ecl#150]
Issue Type: <b>Bug</b>

F12 feature is not working after the latest update

Extension version: 1.1.1
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by GordonSmith** [comment]
Can you retest with the 1.1.4 release of the extension?

**Comment by kattasravankumar** [comment]
1.1.4 has the same issue

**Comment by GordonSmith** [comment]
Dup of #149

**Comment by gmarcan** [comment]
I can now use F12, but $.attribute, or just 'attribute' defined in the same folder is not resolving to the appropriate file
