### ISSUE TITLE
Not recongnizing the ECL compiler anymore

### ISSUE THREAD

**Issue by andrademf** [hpcc-systems/vscode-ecl#154]
I've been using the extension for a couple of months and after the today's (10 Oct) update it's stops to recognize the ECL Compiler.

ECL Extension: 1.2.0
VSCode: 1.37.0

After a rollback to the previous version (1.1.15) it's works fine again.

**Comment by GordonSmith** [comment]
@andrademf can you be more specific?  
Does it stop syntax checking / submitting / auto locating correct version?

**Comment by GordonSmith** [comment]
Resolved in v1.2.1
