### ISSUE TITLE
KEL Syntax Highlighting

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/vscode-ecl#166]
Create the syntax colouring files:
* kel,configuration.json
* kel.tmLanguage.json

**Comment by dehilsterlexis** [comment]
@GordonSmith kel.tmLanguage.json is pretty much done. Just need to go over it with to double check the categories. Need to do the config file.

**Comment by GordonSmith** [comment]
REsolved with:  https://github.com/hpcc-systems/vscode-ecl/pull/180
