### ISSUE TITLE
ECL and KEL syntax colorizers overgeneralizing functions

### ISSUE THREAD

**Issue by dehilsterlexis** [hpcc-systems/vscode-ecl#181]
Currently, the logic to restrict functions to a specific list is not working in both the ECL and KEL syntax grammars.

**Comment by GordonSmith** [comment]
@dehilsterlexis did this get resolved?

**Comment by dehilsterlexis** [comment]
@GordonSmith yes, merged July 1: https://github.com/hpcc-systems/vscode-ecl/pull/182
