### ISSUE TITLE
Feature request: Pin selected launch.json entry to an ECL file

### ISSUE THREAD

**Issue by dcamper** [hpcc-systems/vscode-ecl#184]
Pasting from an email:

"I'm currently working on a project with several BWRs, banging up against Dataland.  Some of the jobs should target a thor cluster, others an hthor cluster.  Is it feasible to have an option in VS Code where the BWR remembers which launch.json config was last used and switch to it when the file comes forward?"

**Comment by GordonSmith** [comment]
This is blocked by:
* https://github.com/microsoft/vscode/issues/82477
* https://github.com/microsoft/vscode/issues/77138
