### ISSUE TITLE
Complex builds are submitting empty bwr

### ISSUE THREAD

**Issue by TimNewport** [hpcc-systems/vscode-ecl#206]
I have had this issue for a while now. When I submit a build that contains are large quantity of other libraries, seemingly where the build path includes a module with many exports, the workunit submits but there is no action associated with the workunit. The ECL bwr is empty in ecl watch. If I run the same bwr from the ECL IDE, same cluster and same branch the build submits as expected. 

![image](https://user-images.githubusercontent.com/14907947/94025958-156b7e80-fd87-11ea-8fab-600b80a57e6e.png)

**Comment by GordonSmith** [comment]
That sounds like a timeout uploading the ECL Archive (if its large and your VPN is slow).  Have you tried increasing the "timeoutSecs" in your launch config?
If you look at the ECL Logs it should show some additional info:
![image](https://user-images.githubusercontent.com/966863/94027705-0b5f7500-fdb3-11ea-8629-dc88d866defb.png)

**Comment by TimNewport** [comment]
My "timeoutSecs": 400, The entire submit takes less than 30 seconds as you can see from the log.  
![image](https://user-images.githubusercontent.com/14907947/94029219-94ae8180-fd8a-11ea-9a43-3a28b6c64bb1.png)

**Comment by GordonSmith** [comment]
I beleive this is resolved with a server config setting

**Comment by TimNewport** [comment]
@GordonSmith  That change did not help the issue with VS Code.

**Comment by mckellyln** [comment]
What ESP are you submitting to ?
I can trace the network traffic maybe to help debug ??

**Comment by TimNewport** [comment]
setting the maxRequestEntityLength="0" on the esp did the trick

**Comment by mckellyln** [comment]
ok, awesome, thanks.
