### ISSUE TITLE
Intermittent: Extension sometimes fails to initialize

### ISSUE THREAD

**Issue by dcamper** [hpcc-systems/vscode-ecl#210]
On occasion, but only just after launching VS Code, the extension seems to fail to integrate with the environment.  The most common manifestation I've seen is a "ecl.submit not found" error when trying to submit code, but when that appears then it becomes obvious that none of the extension's commands are findable.  One workaround for this is to disable/enable the extension.

This problem appeared only recently.  I have not found a way to reliably reproduce this issue.

**Comment by GordonSmith** [comment]
@dcamper there was a new release today (v2.4.0), which may have helped - or by recently do you mean today?

Previously that error happened when there was no ECL Launch configured (I think its fixed/improved today).

**Comment by dcamper** [comment]
It did not happen to me, but:  I noticed the VS Code and extension update this morning and notified Arjuna.  He experienced the problem immediately after updating.

**Comment by GordonSmith** [comment]
I have failed to reproduce on v2.4.0, if anyone has definitive steps please let me know.
