### ISSUE TITLE
No Error Notification/Message

### ISSUE THREAD

**Issue by hebertonbarros** [hpcc-systems/vscode-ecl#240]
For better awareness when developing, I would like to have a functionality where when I syntax check an object/attribute that I have just changed, a "No errors" message (similar to what the ECL IDE produces) is displayed in the VS Code terminal.

I know that as of right now, if it doesn't syntax check, the object we are editing will turn red (telling us that something is not right). However, I have come across a situation where if the there is too much going on inside an object, the syntax check will keep going forever (...checking[1,1]) and the object won't turn red. Then it won't syntax check, and a message will pop up saying that the extension host terminated unexpectedly - no way of knowing whether there is something is wrong with the code. 

![extensionHostTerminated](https://user-images.githubusercontent.com/15935007/110185901-3c6bb900-7dd9-11eb-8bc8-269791090bf3.png)

So for those "bigger" objects, the only way to know what the errors are is by deploying the service and looking at the errors out on the ECL Watch page. 

Having a message stating that syntax check is completed and there are no errors would be nice to have.

Thanks, Heberton.

**Comment by GordonSmith** [comment]
@hebertonbarros sounds like a more significant issue when checking very large/complex code - I would like to reproduce this on my machine as I have never seen the terminated unexpectedly issue before.

**Comment by bythebook** [comment]
I don't get the extension host quitting unexpectedly, but I'm having the same issue as Herberton with the '...checking...' message never going away. From debugging the extension though, I can see that the syntax check does complete, the extension just doesn't clear the message. I have a pull request for this that should fix it.
