### ISSUE TITLE
Syntax Highlight - Outcome of Issue 238?

### ISSUE THREAD

**Issue by hebertonbarros** [hpcc-systems/vscode-ecl#244]
It looks like issue 238 fixed most things but may have introduced another bug? Find original issue here: https://github.com/hpcc-systems/vscode-ecl/issues/238

The problem with the inline dataset/transform was _not_ fixed and now the EXPORT keyword isn't being highlighted anymore. Please see below: 

![image](https://user-images.githubusercontent.com/15935007/110712219-79afbc80-81c6-11eb-9c08-8ed738e5f8bf.png)
![image](https://user-images.githubusercontent.com/15935007/110712228-7caaad00-81c6-11eb-85ee-dcf82c754f2f.png)

**Comment by dehilsterlexis** [comment]
@hebertonbarros @GordonSmith this has been fixed. Thanks for finding this: https://github.com/hpcc-systems/vscode-ecl/pull/242
