### ISSUE TITLE
VS Code - ECL Extension Colorization

### ISSUE THREAD

**Issue by hebertonbarros** [hpcc-systems/vscode-ecl#255]
Hi! 

There are a few keywords that are not being colorized at all and some that are not being colorized correctly. In addition, it looks like we are having some issues with some keywords when used in an inline dataset/transform. Please see below: 

![image](https://user-images.githubusercontent.com/15935007/118165355-cd6a9c00-b3e9-11eb-8b67-17b2b4d75b4e.png)

It would be great if we could have these fixed. Thanks!

**Comment by GordonSmith** [comment]
Resolved with:  https://github.com/hpcc-systems/vscode-ecl/pull/260
