### ISSUE TITLE
Feature Req: "Unreachable" indicator for current cluster

### ISSUE THREAD

**Issue by dcamper** [hpcc-systems/vscode-ecl#268]
Easy to describe:  When the heartbeat code cannot reach the current cluster, display an indicator that the cluster is unreachable.  This could be colorizing the cluster's name (red), or some other indicator that makes sense.

**Comment by GordonSmith** [comment]
Dan is this primarily for initial connection or just general use (like when you drop off a VPN connection)?

**Comment by dcamper** [comment]
This would be primarily for general use rather than initial connection, as a "Connection failed" message appears in the latter case.
