### ISSUE TITLE
Unable to switch target cluster

### ISSUE THREAD

**Issue by clzarecki** [hpcc-systems/vscode-ecl#296]
After restarting VSCode and connecting to the HPCC platform, I am unable to switch my target cluster to something other than the default of hthor. My targetCluster configuration in launch.json is not hthor. When using cmd + shift + p and selecting "ECL: Switch Target Cluster", the command drop down box closes and nothing happens (no option to switch clusters).

**Comment by clzarecki** [comment]
It might have been a issue with the cluster, but it is working now.

**Comment by GordonSmith** [comment]
@clzarecki FYI - you can also click on the cluster name in the status bar to select a different one...

**Comment by clzarecki** [comment]
Thanks for the suggestion. I also tried that at the time and it wasn't working either, which makes me think there might have been a connection issue or something similar that it couldn't retrieve the cluster names. Anyways, it works now, so no problem!
