### ISSUE TITLE
Submit "dirty" content (fake builder window)

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/vscode-ecl#297]

**Comment by GordonSmith** [comment]
When submitting the active windows ECL AND the active window has not been save (new window), create a tmp file and submit that.  This would be analogous to the old builder window.

**Comment by chatst01** [comment]
Can I +1 on this please - one of the main reasons I still haven't fully migrated from IDE - this would be a great feature to have

**Comment by rossmkynch** [comment]
I'd really appreciate this feature!
