### ISSUE TITLE
Submits zero size archives if log file can't be opened

### ISSUE THREAD

**Issue by bythebook** [hpcc-systems/vscode-ecl#298]
Hi,

I've run into an issue where when I submit an ECL job, the worker view shows the loading spinner indefinitely. When I track the worker down in ECLWatch, I find that the plugin has submitted no code, even though there was code in the file I submitted from.

I turned on logs in the plugin and found that the ECL compiler was failing because the default log location was in Program Files on a managed computer. Specifying a log file through the ecl.eclccLogFile setting fixes this issue.

The bug is that when the compiler was failing, the plugin gave no useful error messages and didn't indicate that the worker unit had failed. This took quite a while to track down as a fairly new ECL user.

Thanks!

**Comment by GordonSmith** [comment]
@bythebook I am able to reproduce your issue and will work to promote the error message on submit.

I just wanted to check that you do get the following error in the problems tab:
![image](https://user-images.githubusercontent.com/966863/157821628-4a57d1f8-188a-414e-b56d-7871a0b8bcbb.png)
