### ISSUE TITLE
Can't set compiler

### ISSUE THREAD

**Issue by james-wilson-ln** [hpcc-systems/vscode-ecl#305]
When I click on the compiler version ![image](https://user-images.githubusercontent.com/73425954/168808551-91ad5724-5591-414a-bd0a-29fb36bdc3ac.png)
I get the option to select one of the installed compilers
![image](https://user-images.githubusercontent.com/73425954/168808721-a6c52742-a8a7-4d2e-9be8-e2c2f6e2724f.png)
however when I click on one of the versions (so here I tried 7.12.74) the display stayed with the current version (8.6.10) and that's also what I see in eclcc.log.
This used to work, I'm afraid I don't know exactly when it stopped. I'm on version 2.19 of the extension and 1.67.1 of VSCode.

**Comment by GordonSmith** [comment]
I can reproduce this locally, will investigate...

**Comment by GordonSmith** [comment]
This will be resolved in v2.19.1
