### ISSUE TITLE
ecl.WUShowResults not showing in Settings view

### ISSUE THREAD

**Issue by FranDe01** [hpcc-systems/vscode-ecl#389]
I was having trouble with `WUAuto Open` working on my setup so I came here to look for answers.  I found the PR for ecl.WUShowResults and was able to manually add that to my settings.json, however there isn't an option in the Settings UI to change this value.

I'm using v2.26.2 of the ECL Language extension.

**Comment by ddehilster** [comment]
@FranDe01 let us talk about this so you can show me.

**Comment by dehilsterlexis** [comment]
@FranDe01 this was accidently remove in PR https://github.com/hpcc-systems/vscode-ecl/pull/364
