### ISSUE TITLE
Unable to view OUTPUTs of Workunits in VS Code using ECL Extension 0.0.26

### ISSUE THREAD

**Issue by Wrobelaf** [hpcc-systems/vscode-ecl#76]
The results pane for a Workunit just shows:
_Access Denied -- Valid username and password required!_
Can compile run Run Workunits fine.

Using ClientTools 6.4.8-1

**Comment by newportm** [comment]
I am having the same issue. Before we can start using VS code this one needs to be resolved.
Using ClientTools 6.4.10

**Comment by GordonSmith** [comment]
The current workaround is to set:  `ecl.WUOpenExternal` to true.

FWIW I am personally finding that the displaying of the results in vscode is not very usable due to the lack of real estate and I end up just using the external ECL Watch page.

**Comment by GordonSmith** [comment]
Update:  At the moment I am unable to find any quick way to provide credentials to the embedded ECL Watch page and am defaulting the open WU in an external browser to true.

**Comment by GordonSmith** [comment]
FYI - This will just work with the 7.0 platform as it introduces session management and a automatic redirect to the login window.

Having said that, I think I am leaning towards just embedding the results for a give WU, with links out to the details/ECL Watch page.

**Comment by GordonSmith** [comment]
Closing as this should be resolved with 7.0 platform release and there is a work around for earlier versions.
