### ISSUE TITLE
IntelliSense not working without a reference in the active pane. ECL Extension 0.0.26

### ISSUE THREAD

**Issue by Wrobelaf** [hpcc-systems/vscode-ecl#77]
See Attachment for details.

[RE IntelliSense Issue.zip](https://github.com/hpcc-systems/vscode-ecl/files/1710359/RE.IntelliSense.Issue.zip)

**Comment by GordonSmith** [comment]
In general this is true of any imported module - there isn't any intellisense until the imported module has been "seen" by the compiler (typically by a syntax check).

In your example, does the inellisense start to work after you syntax check it once?

**Comment by GordonSmith** [comment]
Closing as there is a new option to "syntax check on file load" which should resolve this.
