### ISSUE TITLE
Cannot set legacy mode with work spaces

### ISSUE THREAD

**Issue by johnholt** [hpcc-systems/vscode-ecl#86]
Can set for individual folders.  But, when several folders are combined as a workspace the legacy mode setting is not picked up.

**Comment by GordonSmith** [comment]
There is a "workspace" settings section when your working that way:
![image](https://user-images.githubusercontent.com/966863/38151215-46e9a480-345a-11e8-8a67-aab9f22f2455.png)

**Comment by johnholt** [comment]
This worked.  Closing issue.
