### ISSUE TITLE
Set execution target version for selecting plugin version

### ISSUE THREAD

**Issue by johnholt** [hpcc-systems/vscode-ecl#88]
The plugin version used for a syntax check and a compile to produce an archive should be based upon the version reported by the launch server address or the default server address or some version specified by the developer in the work space or folder settings.

**Comment by GordonSmith** [comment]
@johnholt There is some logic which should be doing this already.  The found matching version is echoed out to the "Debug Console"  I will need to install a few client tools versions to see if it is actually working as expected.

**Comment by GordonSmith** [comment]
@johnholt Are you on OSX?  The logic may not be working correctly there...

**Comment by johnholt** [comment]
I am on OS X.

**Comment by GordonSmith** [comment]
FYI At the moment it is not possible to get the current launch confif:  https://github.com/Microsoft/vscode/issues/23564

**Comment by GordonSmith** [comment]
Resolved with:  https://github.com/hpcc-systems/vscode-ecl/pull/155
