### ISSUE TITLE
Fixed errors from imported files not being cleared

### ISSUE THREAD

**Issue by dcamper** [hpcc-systems/vscode-ecl#96]
During syntax check, when errors are reported in files that are imported (not currently being edited) and then fixed, the errors for those imported files are not cleared.  The only workaround I've found is to quit VS Code and restart it.  The errors for those files should be cleared upon a subsequent syntax check.

**Comment by GordonSmith** [comment]
1. ctrl+F7 will clear all the errors (ECL: Clear all reported problems)
2. Clicking on the error should open the file which contained the error, then either syntax checking it (which will happen automatically once opened), or closing it should then remove those errors.

The second behavior is a result of https://github.com/hpcc-systems/vscode-ecl/issues/61

**Comment by dcamper** [comment]
Sorry for the delayed response; I didn't receive a notification that you had posted a reply.

The manual workarounds are fine, but is there a way to automatically perform that behavior?  The current behavior is counter-intuitive to me.  Errors are found and displayed when certain events are triggered, so I would think that a lack of errors (with corresponding display updates) would also be found when the same events are triggered.
